name: Compile LaTeX
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended latexmk
      - name: Compile LaTeX + BibTeX
        run: |
          latexmk -pdf -shell-escape -interaction=nonstopmode main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: report.pdf
          path: main.pdf