name: Compile and Release LaTeX PDF
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-bibtex-extra \
            biber \
            latexmk

      - name: Compile LaTeX
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error -bibtex main.tex

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
          tag_name: "v${{ steps.date.outputs.DATE }}"
          name: "Report ${{ steps.date.outputs.DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}