name: Compile and Release LaTeX PDF
on:
  push:
    branches: [ "main" ]  # Only trigger on pushes to 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX and biblatex
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-bibtex-extra \
            biber \
            latexmk

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error -bibtex main.tex

      - name: Create GitHub Release and Upload PDF
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
          tag_name: "v$(date +'%Y.%m.%d')"  # Auto-tag with today's date (e.g., v2024.06.25)
          draft: false
          prerelease: false